### ISSUE TITLE
[download] Got error: 

### ISSUE THREAD

**Issue by cibernicola** [okio-ai/nendo-example-apps#1]
Just trying it:
`('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))`

Under Windows 10.

**Comment by faradox** [comment]
Hi @cibernicola,

thanks for reporting on this issue.

Please provide some more information on what command you used (`main.py`? colab?) and on your setup (which version of python, which virtual environment, which commands used to install) so we can help you.

Best regards

**Comment by cibernicola** [comment]
Sorry:
Here it goes:
```
virtualenv venv --python=python3.10 
pip install -r requirements.txt
```
Requirements error:

```
INFO: pip is looking at multiple versions of nendo-plugin-classify-core to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement essentia<3.0,>=2.1b6.dev1034 (from nendo-plugin-classify-core) (from versions: 2.1b5.dev416, 2.1b5.dev447, 2.1b5.dev532, 2.1b5.dev707, 2.1b5, 2.1b6.dev90, 2.1b6.dev184, 2.1b6.dev234)
ERROR: No matching distribution found for essentia<3.0,>=2.1b6.dev1034
```
From here installing nendo normally and other requirements manually, then this command:
`python main.py -l https://www.youtube.com/watch?v=9vVcTw-zGsE -p "jazz bebop" -o "uptown_jazz.mp4"`
actually the given yt url `https://www.youtube.com/watch\?v\=OPf0YbXqDm0` gets a 404

and the whole error is:
```
 J:\gpt\music\nendo-example-apps\video-remixer>python main.py -l https://www.youtube.com/watch?v=9vVcTw-zGsE -p "jazz bebop" -o "uptown_jazz.mp4"
ERROR: file:video.f616.mp4: Invalid data found when processing input
ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
video.webm: No such file or directory
Traceback (most recent call last):
  File "J:\gpt\music\nendo-example-apps\video-remixer\main.py", line 167, in <module>
    main(
  File "J:\gpt\music\nendo-example-apps\video-remixer\main.py", line 156, in main
    audio_path = extract_audio(video_path, output_path="audio.mp3")
  File "J:\gpt\music\nendo-example-apps\video-remixer\main.py", line 65, in extract_audio
    subprocess.check_call(cmd)
  File "C:\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-i', 'video.webm', '-q:a', '0', '-map', 'a', '-vn', 'audio.mp3']' returned non-zero exit status 1.
```

**Comment by faradox** [comment]
Seeing your edit, I want to first point you to the [requirements](https://github.com/okio-ai/nendo#requirements) section of the Nendo Core README, which states that we haven't tested running Nendo on windows thoroughly yet and for the time being advise to use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install).

That being said, we are investigating the issue and will get back to you shortly.

**Comment by faradox** [comment]
Hi @cibernicola, sorry for the delay. I tried but wasn't able to reconstruct your error. However, I found some threads in the wild that seem to point to a problem with the versions of `yt-dlp` and `ffmpeg` installed on Windows:

- https://github.com/yt-dlp/yt-dlp/issues/7541
- https://www.reddit.com/r/ffmpeg/comments/unffeh/invalid_data_found_when_processing_input/

Possibly you could find some help there. I'll close this issue for now and again recommend to use WSL, since it's definitely better, also when starting to work with the various nendo plugins.
